before_script:
  - docker info

build_image:
  stage: build
  script:
    - docker build . -t docker.maxiv.lu.se/exi-test
    - docker push docker.maxiv.lu.se/exi-test
  only:
    - master

deploy_image:
  stage: deploy
  script:
  - "curl -H 'Authorization: Bearer gOj9o8s3RapHiThfNbImaFYMDoOKTG' -k --request POST https://ansible.maxiv.lu.se/api/v2/job_templates/23/launch/"
  only:
    - master